/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/99byKVjUZt3
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Blog() {
  return (
    <div className="grid min-h-screen bg-black grid-rows-[auto_1fr_auto] dark:bg-gray-850">
      <header className="bg-black shadow">
        <div className="px-4">
          <div className="flex items-center justify-between h-14">

            <div className="hidden space-x-4 md:flex">

              <Link
                className="text-sm font-medium border border-gray-200 border-indigo-600 rounded-full px-3 py-2 transition-colors hover:bg-indigo-600 hover:text-white dark:border-gray-800"
                href="#"
              >
                Subscribe to Satyam
              </Link>
            </div>
            <div className="flex md:hidden">
              <Button size="sm" variant="ghost">
                Menu
              </Button>
            </div>
          </div>
        </div>
      </header>
      <main className="grid gap-12 py-12 lg:gap-24 lg:py-16 xl:gap-32 xl:py-20">
        <div className="px-4 md:px-6 lg:px-8 xl:px-12">
          <div className="grid gap-4 lg:gap-8">
            <div className="space-y-2">
              <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
                Welcome to the Blog
              </h1>
              <p className="text-gray-500 dark:text-gray-400">The most interesting stories from around the world</p>
            </div>
            <div className="space-y-4">
              <div className="grid gap-2 md:grid-cols-2">
                <div className="flex items-center space-x-2">
                  <img
                    alt="Avatar"
                    className="rounded-full"
                    height={40}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "40/40",
                      objectFit: "cover",
                    }}
                    width={40}
                  />
                  <p className="text-sm font-medium">John Doe</p>
                </div>
                <div className="flex items-center space-x-2 text-sm">
                  <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
                  <span className="mx-1.5 text-gray-300 dark:text-gray-700">•</span>
                  <p className="text-gray-300 underline hover:text-gray-500 dark:hover:text-gray-400">5 min read</p>
                </div>
              </div>
              <div className="[&>p:first-child]:mt-0">
                <p>
                  Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                  throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
                </p>
                <p>
                  Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the
                  place: under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he
                  couldn't seem to stop Jokester.
                </p>
                <p>
                  And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny
                  that they couldn't help but laugh. And once they started laughing, they couldn't stop.
                </p>
              </div>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-4">
                <img
                  alt="Cover image"
                  className="aspect-video overflow-hidden rounded-lg object-cover"
                  height={280}
                  src="/placeholder.svg"
                  width={500}
                />
                <div className="space-y-4">
                  <p>
                    The king thought long and hard, and finally came up with
                    <Link href="#">a brilliant plan</Link>: he would tax the jokes in the kingdom.
                  </p>
                  <blockquote>
                    “After all,” he said, “everyone enjoys a good joke, so it's only fair that they should pay for the
                    privilege.”
                  </blockquote>
                </div>
              </div>
              <div className="space-y-4">
                <img
                  alt="Cover image"
                  className="aspect-video overflow-hidden rounded-lg object-cover"
                  height={280}
                  src="/placeholder.svg"
                  width={500}
                />
                <div className="space-y-4">
                  <p>
                    The king thought long and hard, and finally came up with
                    <Link href="#">a brilliant plan</Link>: he would tax the jokes in the kingdom.
                  </p>
                  <blockquote>
                    “After all,” he said, “everyone enjoys a good joke, so it's only fair that they should pay for the
                    privilege.”
                  </blockquote>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="border-t border-gray-200" />        
      </main>
      <div className="border-t border-gray-200">
        <div className="space-y-2 mb-3">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
            See More from Satyam
          </h1>
          <Button >See All</Button>
        </div>
        <div className="grid gap-10 md:grid-cols-4">
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={140}
            src="/placeholder.svg"
            width={250}
          />
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={140}
            src="/placeholder.svg"
            width={250}
          />
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={140}
            src="/placeholder.svg"
            width={250}
          />
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={140}
            src="/placeholder.svg"
            width={250}
          />
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={140}
            src="/placeholder.svg"
            width={250}
          />
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={140}
            src="/placeholder.svg"
            width={250}
          />
        </div>
      </div>

    </div>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}
