/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/djDYt18IXtV
 */
import Link from "next/link"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Navbar() {
  return (
    <div className="w-full overflow-hidden">
      <header className="w-full">
        <div className="container flex items-center justify-between h-[60px] px-4 md:px-6">
          <Link className="flex items-center space-x-2 font-medium" href="#">
            <FlagIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">Home</span>
          </Link>
          <nav className="hidden space-x-4 md:flex">
            <Link
              className="font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Polls
            </Link>
            <Link
              className="font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Meetings
            </Link>
            <Link
              className="font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Assignments
            </Link>
            <Link
              className="font-medium text-gray-500 transition-colors hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Chat
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Link
              className="flex items-center space-x-2 text-sm font-medium rounded-md bg-gray-100 px-3 py-2 dark:bg-gray-800"
              href="#"
            >
              <UserIcon className="h-4 w-4 rounded-full" />
              <span className="font-semibold">Profile</span>
            </Link>
          </div>
        </div>
      </header>
    </div>
  )
}

function FlagIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}

function UserIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
