/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/C2wY12RGuYp
 */
import Link from "next/link"
import { Avatar, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CardContent, Card } from "@/components/ui/card"

export function Yuj() {
  return (
    <>      
      <section className="w-full py-6 md:py-12 lg:py-16">
        <div className="container grid md:grid-cols-3 gap-6 px-4 md:px-6">
          <div className="flex flex-col gap-2 md:grid md:gap-1 lg:gap-2">
            <div className="space-y-1">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Study Group</h1>
              <p>12 Members <Link className="underline" href="">Check all</Link></p>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Button size="sm">Join Group</Button>
              <Button size="sm" variant="outline">
                Invite
              </Button>
            </div>
          </div>        
          <div className="grid gap-1 text-sm">
            <ul className="grid gap-1 list-disc">
              <li>Computer Science</li>
              <li>Physics</li>
              <li>Mathematics</li>
            </ul>
            <div className="flex items-center gap-2">
              <UsersIcon className="w-4 h-4 fill-current" />
              <div className="grid gap-1 text-xs">
                <div className="flex items-center gap-1">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  </Avatar>
                  <time className="text-xs text-gray-500 dark:text-gray-400">1 min ago</time>
                </div>
                <div className="grid gap-0.5">
                  <p className="font-semibold">Alice Johnson</p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    Hey everyone! Looking forward to studying together.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <Button className="">Check Recent Happenings</Button>
        </div>
      </section>      
      <div className="grid gap-6 p-6 lg:grid-cols-3 xl:gap-10">
      <Card className="bg-gradient-to-r from-pink-500 to-purple-500">
            <CardContent className="p-6">
              <div className="space-y-4 ">
                <h2 className="text-2xl font-bold">Create New event</h2>
                <p className="text-gray-500 dark:text-black">
                want a new service? Post , edit and create here.
                </p>
                <Button className="w-full">Create New</Button>
              </div>
            </CardContent>
          </Card>
          <div className="space-y-4">
            <h1 className="text-3xl font-bold">Welcome to the Collaboration Platform</h1>
            <p className="text-gray-500 dark:text-gray-400">
              This is your one-stop destination for collaboration within the organization. Connect with your colleagues,
              share knowledge, and work together seamlessly.
            </p>
          </div>          
          <Card>
            <CardContent className="p-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold">Discussion/ Confession</h2>
                <p className="text-gray-500 dark:text-gray-400">
                  Have a question? Want to discuss a topic? Start a discussion and get insights from your peers.
                </p>
                <Button className="w-full">See One</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold">Create a Meet</h2>
                <p className="text-gray-500 dark:text-gray-400">
                  Schedule a meeting with your team, share the agenda, and collaborate effectively.
                </p>
                <Button className="w-full">Make one</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold">See Polls</h2>
                <p className="text-gray-500 dark:text-gray-400">
                  Let your team vote! Create a poll to gather feedback or make decisions collaboratively.
                </p>
                <Button className="w-full">See Poll</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold">Buy Old</h2>
                <p className="text-gray-500 dark:text-gray-400">
                 want to sell ur old stuff? Post here.
                </p>
                <Button className="w-full">Buy</Button>
              </div>
            </CardContent>
          </Card>
          <div className="space-y-4">
            <h1 className="text-3xl font-bold">Welcome to the Collaboration Platform</h1>
            <p className="text-gray-500 dark:text-gray-400">
              This is your one-stop destination for collaboration within the organization. Connect with your colleagues,
              share knowledge, and work together seamlessly.
            </p>
          </div>
        </div>
      <aside className="w-full py-6 md:py-12">
        <div className="container px-4 md:px-6">
          <div className="space-y-2">
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Members</h2>
            <p className="text-gray-500 dark:text-gray-400">Meet the members of the study group.</p>
          </div>
          <div>

          </div>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">
            <div className="flex items-center gap-2">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
              </Avatar>
              <div className="grid gap-1.5 text-sm">
                <div className="font-semibold">Alice Johnson</div>
                <div className="text-xs text-gray-500 dark:text-gray-400">Joined: 2 days ago</div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
              </Avatar>
              <div className="grid gap-1.5 text-sm">
                <div className="font-semibold">Bob Smith</div>
                <div className="text-xs text-gray-500 dark:text-gray-400">Joined: 1 week ago</div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
              </Avatar>
              <div className="grid gap-1.5 text-sm">
                <div className="font-semibold">Emily Davis</div>
                <div className="text-xs text-gray-500 dark:text-gray-400">Joined: 1 month ago</div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Avatar className="w-10 h-10 border">
                <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
              </Avatar>
              <div className="grid gap-1.5 text-sm">
                <div className="font-semibold">Mark Wilson</div>
                <div className="text-xs text-gray-500 dark:text-gray-400">Joined: 3 months ago</div>
              </div>
            </div>
          </div>
        </div>
      </aside>
    </>
  )
}


function GraduationCapIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 10v6M2 10l10-5 10 5-10 5z" />
      <path d="M6 12v5c3 3 9 3 12 0v-5" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
