/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gbIefo6orRs
 */
import { Button } from "@/components/ui/button";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Textarea } from "@/components/ui/textarea";

export function Chat() {
  return (
    <div className="flex flex-row">
      <div className="flex flex-col gap-2 w-1/5 p-5 items-center h-[100vh]">
        <input
          type="text"
          placeholder="Search name..."
          className="p-2 mb-4 bg-slate-900 rounded-lg mt-4 mx-auto"
        />
        <ul className="flex flex-col gap-2 w-full overflow-y-auto">
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
          <li className="border border-white rounded-lg w-full p-2 bg-slate-700">
            Satyam
          </li>
        </ul>
      </div>
      <div className="flex flex-col border border-gray-200 rounded-lg overflow-hidden dark:border-gray-800 w-4/5">
        <div>
          <div className="flex items-center p-4 border-b gap-2">
            <Button className="rounded-full w-8 h-8 p-0" size="icon">
              <ChevronLeftIcon className="w-4 h-4" />
              <span className="sr-only">Back</span>
            </Button>
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <h2 className="text-base font-semibold leading-none sm:text-sm md:text-base">
                Conversation with Olivia
              </h2>
            </div>
            <Button
              className="ml-auto rounded-full w-8 h-8"
              size="icon"
              variant="ghost"
            >
              <VideoIcon className="w-4 h-4" />
              <span className="sr-only">Video call</span>
            </Button>
            <Button
              className="rounded-full w-8 h-8"
              size="icon"
              variant="ghost"
            >
              <PhoneIcon className="w-4 h-4" />
              <span className="sr-only">Call</span>
            </Button>
          </div>
          <div className="flex-1 flex flex-col p-4 space-y-4 overflow-auto">
            <div className="flex items-start flex-row-reverse space-x-2">
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-1000 p-3 text-sm break-words  dark:bg-black dark:text-gray-1000">
                <div>
                  Hi, let's have a meeting tomorrow to discuss the project. I've
                  been reviewing the project details and have some ideas I'd
                  like to share. It's crucial that we align on our next steps to
                  ensure the project's success.
                </div>
                <div className="text-xs mt-2">Now</div>
              </div>
              <Avatar className="w-10 h-10 order-2">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
            <div className="flex items-start space-x-2">
              <Avatar className="w-10 h-10">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Please come prepared with any questions or insights you may
                  have. Looking forward to our meeting!
                </div>
                <div className="text-xs mt-2">2:35 PM</div>
              </div>
            </div>
            <div className="flex items-start space-x-2">
              <Avatar className="w-10 h-10">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Please come prepared with any questions or insights you may
                  have. Looking forward to our meeting!
                </div>
                <div className="text-xs mt-2">2:35 PM</div>
              </div>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Please come prepared with any questions or insights you may
                  have. Looking forward to our meeting!
                </div>
                <div className="text-xs mt-2">2:35 PM</div>
              </div>
            </div>
            <div className="flex items-start space-x-2">
              <Avatar className="w-10 h-10">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Please come prepared with any questions or insights you may
                  have. Looking forward to our meeting!
                </div>
                <div className="text-xs mt-2">2:35 PM</div>
              </div>
            </div>
            <div className="flex items-start flex-row-reverse space-x-2">
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-1000 p-3 text-sm break-words  dark:bg-black dark:text-gray-1000">
                <div>
                  Absolutely, Olivia! I'll make sure to compile our progress
                  report and will be ready to discuss our next steps. Thanks for
                  the heads up.
                </div>
                <div className="text-xs mt-2">2:36 PM</div>
              </div>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-1000 p-3 text-sm break-words  dark:bg-black dark:text-gray-1000">
                <div>
                  Absolutely, Olivia! I'll make sure to compile our progress
                  report and will be ready to discuss our next steps. Thanks for
                  the heads up.
                </div>
                <div className="text-xs mt-2">2:36 PM</div>
              </div>
              <Avatar className="w-10 h-10 order-2">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
            <div className="flex items-start space-x-2">
              <Avatar className="w-10 h-10">
                <AvatarImage alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Hi team! Just a reminder that we have our weekly sync meeting
                  tomorrow at 10 am. We'll be discussing our progress on the
                  current sprint and any blockers we might have. See you all
                  there!
                </div>
                <div className="text-xs mt-2">2:30 PM</div>
              </div>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Hi team! Just a reminder that we have our weekly sync meeting
                  tomorrow at 10 am. We'll be discussing our progress on the
                  current sprint and any blockers we might have. See you all
                  there!
                </div>
                <div className="text-xs mt-2">2:30 PM</div>
              </div>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Hi team! Just a reminder that we have our weekly sync meeting
                  tomorrow at 10 am. We'll be discussing our progress on the
                  current sprint and any blockers we might have. See you all
                  there!
                </div>
                <div className="text-xs mt-2">2:30 PM</div>
              </div>
              <div className="flex flex-col max-w-[75%] rounded-lg bg-gray-200 p-3 text-sm break-words dark:bg-gray-800">
                <div>
                  Hi team! Just a reminder that we have our weekly sync meeting
                  tomorrow at 10 am. We'll be discussing our progress on the
                  current sprint and any blockers we might have. See you all
                  there!
                </div>
                <div className="text-xs mt-2">2:30 PM</div>
              </div>
            </div>
          </div>
          <div className="flex items-center p-4 border-t">
            <Button
              className="rounded-full w-8 h-8"
              size="icon"
              variant="ghost"
            >
              <PaperclipIcon className="w-4 h-4" />
              <span className="sr-only">Attach</span>
            </Button>
            <Button
              className="rounded-full w-8 h-8"
              size="icon"
              variant="ghost"
            >
              <SmileIcon className="w-4 h-4" />
              <span className="sr-only">Emoji</span>
            </Button>
            <Button
              className="rounded-full w-8 h-8"
              size="icon"
              variant="ghost"
            >
              <MicIcon className="w-4 h-4" />
              <span className="sr-only">Record voice message</span>
            </Button>
            <Textarea
              className="flex-1 min-h-0 text-sm rounded-xl resize-none"
              placeholder="Type a message"
            />
            <Button className="rounded-full w-8 h-8" size="icon">
              <SendIcon className="w-4 h-4" />
              <span className="sr-only">Send</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  );
}

function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 8-6 4 6 4V8Z" />
      <rect width="14" height="12" x="2" y="6" rx="2" ry="2" />
    </svg>
  );
}

function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  );
}

function PaperclipIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48" />
    </svg>
  );
}

function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  );
}

function MicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  );
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  );
}
