/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fGWUnIvx4De
 */
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function Discussion() {
  return (
    <div className="grid gap-4 lg:grid-cols-1 p-10">
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-2xl font-semibold">
            How to make the perfect cup of coffee
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            This is the place to discuss your tips and tricks for brewing the
            best coffee.
          </p>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold">Original Post</h2>
          <p>
            I've been experimenting with different coffee beans and brewing
            methods, and I think I've finally found the perfect cup of coffee. I
            use freshly ground medium roast beans and a pour-over method. The
            result is a smooth and flavorful cup that really highlights the
            nuances of the beans. What about you? How do you like to make your
            coffee?
          </p>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold">Comments</h2>
          <div className="grid gap-4">
            <div className="flex items-start gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1.5">
                <div className="space-y-0.25">
                  <span className="font-semibold">Alice</span>
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    2 minutes ago
                  </span>
                </div>
                <p>
                  I love a good cup of coffee in the morning. I usually go for a
                  dark roast and use a French press. It makes the coffee rich
                  and bold, which is just how I like it.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1.5">
                <div className="space-y-0.25">
                  <span className="font-semibold">Bob</span>
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    5 minutes ago
                  </span>
                </div>
                <p>
                  I'm a fan of light roasts, and I use a drip coffee maker to
                  brew my morning cup. It brings out the more delicate flavors
                  of the beans, and I find it to be a great way to start the
                  day.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold">Add your comment</h2>
          <form>
            <div className="space-y-2">
              <Label className="sr-only" htmlFor="comment">
                Comment
              </Label>
              <Textarea
                className="min-h-[100px] dark:bg-gray-950"
                id="comment"
                placeholder="What are your thoughts? Type @ to mention someone..."
              />
            </div>
            <Button type="submit">Post comment</Button>
          </form>
        </div>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-2xl font-semibold">
            Best hiking trails in the area
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            Let's share our favorite trails and hidden gems. Whether you're a
            casual stroller or a seasoned hiker, there's something for everyone.
          </p>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold">Original Post</h2>
          <p>
            I'm always on the lookout for new trails to explore, and I thought
            it would be great to create a space where we can share our
            recommendations and experiences. I'll start by mentioning the Oak
            Valley Trail, which offers stunning views of the surrounding
            countryside and is perfect for a leisurely walk. What are your
            favorite trails?
          </p>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold">Comments</h2>
          <div className="grid gap-4">
            <div className="flex items-start gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1.5">
                <div className="space-y-0.25">
                  <span className="font-semibold">Carol</span>
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    2 minutes ago
                  </span>
                </div>
                <p>
                  Thanks for starting this discussion! I'm a big fan of the Pine
                  Ridge Trail, especially during the spring when the wildflowers
                  are in bloom. The trail meanders through a variety of
                  landscapes, and the birdwatching opportunities are fantastic.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1.5">
                <div className="space-y-0.25">
                  <span className="font-semibold">David</span>
                  <span className="text-sm text-gray-500 dark:text-gray-400">
                    5 minutes ago
                  </span>
                </div>
                <p>
                  I've hiked the Eagle Peak Trail a few times, and it always
                  offers a good workout with some steep sections. The payoff is
                  the panoramic view from the summit, which is absolutely worth
                  the effort. Looking forward to hearing about everyone else's
                  favorite trails!
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <h2 className="text-xl font-semibold">Add your comment</h2>
          <form>
            <div className="space-y-2">
              <Label className="sr-only" htmlFor="comment">
                Comment
              </Label>
              <Textarea
                className="min-h-[100px] dark:bg-gray-950"
                id="comment"
                placeholder="What are your thoughts? Type @ to mention someone..."
              />
            </div>
            <Button type="submit">Post comment</Button>
          </form>
        </div>
      </div>
    </div>
  );
}
