/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Nny4fK3jLwz
 */
import { MdOutlineVerticalAlignTop } from "react-icons/md";

export function Groups() {
  return (
    <div className="flex flex-col m-auto">
      <input
        type="text"
        placeholder="Search ur Yuj..."
        className="p-2 mb-4 w-2/5 bg-slate-900 rounded-lg mt-4 mx-auto"
      />
      <section className="w-full py-6 md:py-12">
        <div className=" grid max-w-5xl items-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-2 lg:text-left xl:max-w-6xl xl:gap-10">
          <div className="space-y-4 h-full">
            <div className="space-y-3 sticky top-10 ">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                The Groups of ur College
              </h2>
              <p className="text-gray-500 dark:text-gray-400">
                Join one or request the admin.
              </p>
              <img
                alt="Water"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="400"
                src="/placeholder.svg"
                width="400"
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 md:gap-8">
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Electric</div>
                <div className="text-sm text-gray-500">Electricity</div>
              </div>
              <img
                alt="Electric"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 150</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Fire</div>
                <div className="text-sm text-gray-500">Flames</div>
              </div>
              <img
                alt="Fire"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 140</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Fire</div>
                <div className="text-sm text-gray-500">Flames</div>
              </div>
              <img
                alt="Fire"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 140</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Fire</div>
                <div className="text-sm text-gray-500">Flames</div>
              </div>
              <img
                alt="Fire"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 140</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Fire</div>
                <div className="text-sm text-gray-500">Flames</div>
              </div>
              <img
                alt="Fire"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 140</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Water</div>
                <div className="text-sm text-gray-500">Aquatic</div>
              </div>
              <img
                alt="Water"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 160</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Grass</div>
                <div className="text-sm text-gray-500">Greenery</div>
              </div>
              <img
                alt="Grass"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 155</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Psychic</div>
                <div className="text-sm text-gray-500">Mind</div>
              </div>
              <img
                alt="Psychic"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 145</div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <div className="font-semibold">Rock</div>
                <div className="text-sm text-gray-500">Solid</div>
              </div>
              <img
                alt="Rock"
                className="mx-auto rounded-xl overflow-hidden object-cover border border-gray-200 aspect-square dark:border-gray-800"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <div className="text-sm text-gray-500">Characters: 150</div>
            </div>
          </div>
        </div>
      </section>
      <span className="fixed right-10 bottom-10 border border-white rounded-full p-3">
        <MdOutlineVerticalAlignTop size={40} />
      </span>
    </div>
  );
}
