/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Nny4fK3jLwz
 */
import { MdOutlineVerticalAlignTop } from "react-icons/md";
import Image from "next/image";
import data from "@/lib/data.json";

export function Groups() {
  const groups = data.organisation.yujs;
  return (
    <div id="top" className="flex flex-col m-auto">
      <input
        type="text"
        placeholder="Search ur Yuj..."
        className="p-2 mb-4 w-2/5 bg-slate-900 rounded-lg mt-4 mx-auto"
      />
      <section className="w-full py-6 md:py-12">
        <div className=" grid max-w-5xl items-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:grid-cols-2 lg:text-left xl:max-w-6xl xl:gap-10">
          <div className="space-y-4 h-full">
            <div className="space-y-3 sticky top-10 ">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                The Groups of ur College
              </h2>
              <p className="text-gray-500 dark:text-gray-400">
                Join one or request the admin.
              </p>
              <Image
                src={"https://www.iitbbs.ac.in/images/campus-view-360.jpg"}
                height={400}
                width={400}
                alt=""
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 md:gap-8">
            {groups.map((group, index) => (
              <a
                target="none"
                href={`/savyuj/groups/${group.id}`}
                key={index}
                className="flex flex-col gap-2"
              >
                <div className="flex items-center gap-2">
                  <div className="font-semibold">{group.name}</div>
                  <div className="text-sm text-gray-500">
                    {group.description}
                  </div>
                </div>
                <Image
                  src={group.image || ""}
                  height={200}
                  width={200}
                  alt=""
                />
                <div className="text-sm text-gray-500">
                  Members: {Object.keys(group.members).length}
                </div>
              </a>
            ))}
          </div>
        </div>
      </section>
      <span
        onClick={() => {
          window.scrollTo({
            top: 0,
          });
        }}
        className="fixed bg-black right-10 bottom-10 border border-white rounded-full p-3"
      >
        <MdOutlineVerticalAlignTop size={40} />
      </span>
    </div>
  );
}
