/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oVKGa9E06Wn
 */
import { Avatar } from "@/components/ui/avatar"

export function Profile() {
  return (
    <>
      <div className="bg-black py-6 w-full">
        <div className=" px-4 md:px-6">
          <div className="grid gap-4 md:gap-8 items-center md:grid-cols-2 lg:gap-12">
            <div className="flex items-center space-x-4">
              <Avatar className="border h-24 w-24 border-white shadow-lg">
                <img
                  alt="Avatar"
                  className="rounded-full object-cover"
                  height="96"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "96/96",
                    objectFit: "cover",
                  }}
                  width="96"
                />
              </Avatar>
              <div className="space-y-1.5">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl xl:text-5xl">Alice Smith</h1>
                <div className="flex items-center space-x-2 text-sm text-gray-500 dark:text-gray-400">
                  <span className="font-medium">Computer Science</span>
                  <span className="text-gray-300">•</span>
                  <span>Class of 2023</span>
                </div>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl xl:text-xl">Edorsement</h1>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl xl:text-xl">Stars</h1>

              </div>
            </div>
            <div className="grid gap-4 text-sm text-gray-500 md:gap-2 md:text-base lg:text-base/2 dark:text-gray-400">
              <div className="space-y-2">
                <h2 className="text-lg font-semibold">Bio</h2>
                <p className="max-w-prose">
                  Passionate about using technology to solve real-world problems. Currently exploring web development
                  and machine learning.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="w-full py-6">
        <div className=" px-4 md:px-6">
          <div className="grid gap-6 lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-xl font-semibold">Education</h2>
              <div className="grid gap-1 text-sm text-gray-500 md:grid-cols-2 md:text-base dark:text-gray-400">
                <div>
                  <h3 className="font-medium">Harvard University</h3>
                  <p className="text-xs">Bachelor of Computer Science</p>
                </div>
                
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-xl font-semibold">Fest & Societies</h2>
              <div className="flex flex-wrap gap-4.5">
                <div className="rounded-lg bg-gray-100 m-1 px-3 py-1 text-sm dark:bg-gray-800">fest name</div>
                <div className="rounded-lg bg-gray-100 m-1 px-3 py-1 text-sm dark:bg-gray-800">fest name</div>
                <div className="rounded-lg bg-gray-100 m-1 px-3 py-1 text-sm dark:bg-gray-800">fest name</div>
                <div className="rounded-lg bg-gray-100 m-1 px-3 py-1 text-sm dark:bg-gray-800">fest name</div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
      
    </>
  )
}
