/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oVKGa9E06Wn
 */
import { Avatar } from "@/components/ui/avatar";
import data from "@/lib/data.json";
import Image from "next/image";
import Link from "next/link";
export function Profile() {
  return (
    <>
      <div className="bg-black py-6 w-full">
        <div className=" px-4 md:px-6">
          <div className="grid gap-4 md:gap-8 items-center md:grid-cols-2 lg:gap-12">
            <div className="flex items-center space-x-4">
              <Avatar className="border h-24 w-24 border-white shadow-lg">
                <Image
                  src={data.Profile.img}
                  height={96}
                  width={96}
                  alt="profile"
                />
              </Avatar>
              <div className="space-y-1.5">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl xl:text-5xl">
                  {data.Profile.name}
                </h1>
                <div className="flex items-center space-x-2 text-sm text-gray-500 dark:text-gray-400">
                  <span className="font-medium">{data.Profile.Batch}</span>
                </div>
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl xl:text-xl">
                  Stars <span>{data.Profile.stars}</span>
                </h1>
              </div>
            </div>
            <div className="grid gap-4 text-sm text-gray-500 md:gap-2 md:text-base lg:text-base/2 dark:text-gray-400">
              <div className="space-y-2">
                <h2 className="text-lg font-semibold">Bio</h2>
                <p className="max-w-prose">{data.Profile.Bio}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="w-full py-6">
        <div className=" px-4 md:px-6">
          <div className="grid grid-cols-2 gap-6 lg:gap-12">
            <div className="space-y-2">
              <h2 className="text-xl font-semibold">Education</h2>
              <div className="grid grid-cols-1 gap-1 text-sm text-gray-500 md:text-base dark:text-gray-400">
                {data.Profile.Education.map((item, index) => (
                  <div className="m-2 p-2 rounded-lg" key={index}>
                    <h3 className="font-medium">{item.degree}</h3>
                    <p className=" text-xs">{item.school}</p>
                  </div>
                ))}
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-xl font-semibold">Groups</h2>
              <div className="flex flex-wrap gap-4.5">
                {/* <div className="rounded-lg bg-gray-100 m-1 px-3 py-1 text-sm dark:bg-gray-800">fest name</div> */}
                {data.Profile.Groups.map((item, index) => (
                  <Link href={"/savyuj/groups/" + item.id} key={index}>
                    <div
                      className="rounded-lg bg-gray-100 m-1 px-3 py-1 text-sm dark:bg-gray-800"
                      key={index}
                    >
                      {item.name}
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
