/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/C2wY12RGuYp
 */
"use client";
import Link from "next/link";
import { Avatar, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CardContent, Card } from "@/components/ui/card";
import data from "@/lib/data.json";
import { log } from "util";
export default function Yuj({ yuj }: { yuj: string }) {
  const ourYuj = data.organisation.yujs.find((group) => group.id === yuj);

  return (
    <div>
      <section className="w-full py-6 md:py-12 lg:py-16">
        <div className=" grid md:grid-cols-3 gap-6 px-4 md:px-6">
          <div className="flex flex-col gap-2 md:grid md:gap-1 lg:gap-2">
            <div className="space-y-1">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                {ourYuj?.name}
              </h1>
              <p>
                {Object.keys(ourYuj?.members || "All").length} Members
                <Link className="underline mx-2" href="">
                  Check all
                </Link>
              </p>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Button size="sm" variant="outline">
                Invite
              </Button>
            </div>
          </div>
          <div className="grid gap-1 text-sm">
            <div className="flex items-center gap-2">
              <div className="grid gap-1 text-xs">
                <div className="flex items-center gap-1">
                  <span>Owner</span>
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  </Avatar>
                  <a
                    target="none"
                    href={`/profile/${(ourYuj?.admin as { name: string; id: string }).id}`}
                    className="text-xs text-gray-500 dark:text-gray-400"
                  >
                    {(ourYuj?.admin as { name: string; id: string }).name}
                  </a>
                </div>
                <div className="flex items-center gap-1">
                  <span>Mods:</span>
                  <span className="text-xs text-gray-500 dark:text-gray-400">
                    {ourYuj?.mods &&
                      Object.keys(ourYuj.mods)
                        .slice(0, 4)
                        .map((mod, index) => (
                          <a
                            target="none"
                            href={`/profile/${ourYuj?.mods[mod as keyof typeof ourYuj.mods]}`}
                            key={index}
                            className="mx-1"
                          >
                            {mod}
                          </a>
                        ))}
                  </span>
                </div>
              </div>
            </div>
            <ul className="grid gap-1 list-disc">
              {Object.keys(ourYuj?.SocialMedia || {}).map((key) => (
                <li className="m-1" key={key}>
                  <a
                    target="none"
                    href={
                      ourYuj?.SocialMedia[
                        key as keyof typeof ourYuj.SocialMedia
                      ]
                    }
                  >
                    {key}
                  </a>
                </li>
              ))}
            </ul>
          </div>
          <Button className="">Check Recent Happenings</Button>
        </div>
      </section>
      <div className="grid gap-6 p-6 lg:grid-cols-3 xl:gap-10">
        <Card className="bg-gradient-to-r from-pink-500 to-purple-500">
          <CardContent className="p-6">
            <div className="space-y-4 ">
              <h2 className="text-2xl font-bold">Create New event</h2>
              <p className="text-gray-500 dark:text-black">
                want a new service? Post , edit and create here.
              </p>
              <Button className="w-full">Create New</Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">Discussion/ Confession</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Have a question? Want to discuss a topic? Start a discussion and
                get insights from your peers.
              </p>
              <Button className="w-full">See One</Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">Create a Meet</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Schedule a meeting with your team, share the agenda, and
                collaborate effectively.
              </p>
              <Button className="w-full">Make one</Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">See Polls</h2>
              <p className="text-gray-500 dark:text-gray-400">
                Let your team vote! Create a poll to gather feedback or make
                decisions collaboratively.
              </p>
              <Button className="w-full">See Poll</Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">Buy Old</h2>
              <p className="text-gray-500 dark:text-gray-400">
                want to sell ur old stuff? Post here.
              </p>
              <Button className="w-full">Buy</Button>
            </div>
          </CardContent>
        </Card>
      </div>
      <aside className="w-full py-6 md:py-12">
        <div className=" px-4 md:px-6">
          <div className="space-y-2">
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">
              Members
            </h2>
            <p className="text-gray-500 dark:text-gray-400">
              Meet the members of the study group.
            </p>
          </div>
          <div></div>
          <div className="grid gap-1 md:grid-cols-2 lg:grid-cols-5">
            {Object.entries(ourYuj?.members || {}).map(
              ([member, value], index) => (
                <a
                  target="none"
                  href={`/profile/${value}`}
                  className=" flex justify-left items-center p-1"
                  key={index}
                >
                  <Avatar>
                    <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  </Avatar>
                  <div className="mx-1 text-sm font-semibold">{member}</div>
                </a>
              ),
            )}
          </div>
        </div>
      </aside>
    </div>
  );
}

function UsersIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}
